export const FamilleProduitsActionType = {
  GET_ERRORS: "GET_ERRORS",
  GET_FAMILLES_PRODUITS: "GET_FAMILLES_PRODUITS",
  ADD_FAMILLE_PRODUIT_SUCCESS: "ADD_FAMILLE_PRODUIT_SUCCESS",
  ADD_FAMILLE_PRODUIT_FAILED: "ADD_FAMILLE_PRODUIT_FAILED",
  UPDATE_FAMILLE_PRODUIT_SUCCESS: "UPDATE_FAMILLE_PRODUIT_SUCCESS",
  UPDATE_FAMILLE_PRODUIT_FAILED: "UPDATE_FAMILLE_PRODUIT_FAILED",
  DELETE_FAMILLE_PRODUIT_SUCCESS: "DELETE_FAMILLE_PRODUIT_SUCCESS",
  DELETE_FAMILLE_PRODUIT_FAILED: "DELETE_FAMILLE_PRODUIT_FAILED",
  ANNULER_ACTION: "ANNULER_ACTION",
};
