export const ServiceFacturableActionType = {
  GET_ERRORS: "GET_ERRORS",
  GET_SERVICES_FACTURABLES: "GET_SERVICES_FACTURABLES",
  ADD_SERVICE_FACTURABLE_SUCCESS: "ADD_SERVICE_FACTURABLE_SUCCESS",
  ADD_SERVICE_FACTURABLE_FAILED: "ADD_SERVICE_FACTURABLE_FAILED",
  UPDATE_SERVICE_FACTURABLE_SUCCESS: "UPDATE_SERVICE_FACTURABLE_SUCCESS",
  UPDATE_SERVICE_FACTURABLE_FAILED: "UPDATE_SERVICE_FACTURABLE_FAILED",
  DELETE_SERVICE_FACTURABLE_SUCCESS: "DELETE_SERVICE_FACTURABLE_SUCCESS",
  DELETE_SERVICE_FACTURABLE_FAILED: "DELETE_SERVICE_FACTURABLE_FAILED",
  ANNULER_ACTION_SF: "ANNULER_ACTION_SF",
};
