export const GrpStatutsActionType = {
  GET_ERRORS: "GET_ERRORS",
  GET_GRPS_STATUTS: "GET_GRPS_STATUTS",
  ADD_GRP_STATUTS_SUCCESS: "ADD_GRP_STATUTS_SUCCESS",
  ADD_GRP_STATUTS_FAILED: "ADD_GRP_STATUTS_FAILED",
  UPDATE_GRP_STATUTS_SUCCESS: "UPDATE_GRP_STATUTS_SUCCESS",
  UPDATE_GRP_STATUTS_FAILED: "UPDATE_GRP_STATUTS_FAILED",
  DELETE_GRP_STATUTS_SUCCESS: "DELETE_GRP_STATUTS_SUCCESS",
  DELETE_GRP_STATUTS_FAILED: "DELETE_GRP_STATUTS_FAILED",
  ANNULER_ACTION_GS: "ANNULER_ACTION_GS",
};
