export const CategorieServiceActionType = {
  GET_ERRORS: "GET_ERRORS",
  GET_CATEGORIES_SERVICE: "GET_CATEGORIES_SERVICE",
  ADD_CATEGORIE_SERVICE_SUCCESS: "ADD_CATEGORIE_SERVICE_SUCCESS",
  ADD_CATEGORIE_SERVICE_FAILED: "ADD_CATEGORIE_SERVICE_FAILED",
  UPDATE_CATEGORIE_SERVICE_SUCCESS: "UPDATE_CATEGORIE_SERVICE_SUCCESS",
  UPDATE_CATEGORIE_SERVICE_FAILED: "UPDATE_CATEGORIE_SERVICE_FAILED",
  DELETE_CATEGORIE_SERVICE_SUCCESS: "DELETE_CATEGORIE_SERVICE_SUCCESS",
  DELETE_CATEGORIE_SERVICE_FAILED: "DELETE_CATEGORIE_SERVICE_FAILED",
  ANNULER_ACTION_CS: "ANNULER_ACTION_CS",
};
