export const GrpMotifsActionType = {
  GET_ERRORS: "GET_ERRORS",
  GET_GRPS_MOTIFS: "GET_GRPS_MOTIFS",
  ADD_GRP_MOTIFS_SUCCESS: "ADD_GRP_MOTIFS_SUCCESS",
  ADD_GRP_MOTIFS_FAILED: "ADD_GRP_MOTIFS_FAILED",
  UPDATE_GRP_MOTIFS_SUCCESS: "UPDATE_GRP_MOTIFS_SUCCESS",
  UPDATE_GRP_MOTIFS_FAILED: "UPDATE_GRP_MOTIFS_FAILED",
  DELETE_GRP_MOTIFS_SUCCESS: "DELETE_GRP_MOTIFS_SUCCESS",
  DELETE_GRP_MOTIFS_FAILED: "DELETE_GRP_MOTIFS_FAILED",
  ANNULER_ACTION_GM: "ANNULER_ACTION_GM",
};
