export const ThemeActionType = {
  GET_ERRORS: "GET_ERRORS",
  GET_THEMES: "GET_THEMES",
  ADD_THEME_SUCCESS: "ADD_THEME_SUCCESS",
  ADD_THEME_FAILED: "ADD_THEME_FAILED",
  UPDATE_THEME_SUCCESS: "UPDATE_THEME_SUCCESS",
  UPDATE_THEME_FAILED: "UPDATE_THEME_FAILED",
  DELETE_THEME_SUCCESS: "DELETE_THEME_SUCCESS",
  DELETE_THEME_FAILED: "DELETE_THEME_FAILED",
  CANCEL_ACTION: "CANCEL_ACTION",
};
