export const ServiceActionType = {
  GET_ERRORS: "GET_ERRORS",
  GET_SERVICES: "GET_SERVICES",
  ADD_SERVICE_SUCCESS: "ADD_SERVICE_SUCCESS",
  ADD_SERVICE_FAILED: "ADD_SERVICE_FAILED",
  UPDATE_SERVICE_SUCCESS: "UPDATE_SERVICE_SUCCESS",
  UPDATE_SERVICE_FAILED: "UPDATE_SERVICE_FAILED",
  DELETE_SERVICE_SUCCESS: "DELETE_SERVICE_SUCCESS",
  DELETE_SERVICE_FAILED: "DELETE_SERVICE_FAILED",
  ANNULER_ACTION_SE: "ANNULER_ACTION_SE",
};
