export const ReportingActionType = {
  GET_ERRORS: "GET_ERRORS",
  GET_NBR_MARKETS: "GET_NBR_MARKETS",
  GET_NBR_FAMILLES_PRODUITS: "GET_NBR_FAMILLES_PRODUITS",
  GET_NBR_TYPES_CLIENT: "GET_NBR_TYPES_CLIENT",
  GET_NBR_CARTES: "GET_NBR_CARTES",
  GET_THEMES: "GET_THEMES",
  GET_CATEGORIES_SERVICE: "GET_CATEGORIES_SERVICE",
  GET_GRPS_STATUTS: "GET_GRPS_STATUTS",
  GET_GRPS_MOTIFS: "GET_GRPS_MOTIFS",
  GET_NBR_CARTES_PAR_THEME: "GET_NBR_CARTES_PAR_THEME",
  GET_NBR_SERVICES_PAR_CATEGORIE_SERVICE:
    "GET_NBR_SERVICES_PAR_CATEGORIE_SERVICE",
  GET_NBR_SERVICES_PAR_GRP_STATUTS: "GET_NBR_SERVICES_PAR_GRP_STATUTS",
  GET_NBR_SERVICES_PAR_GRP_MOTIFS: "GET_NBR_SERVICES_PAR_GRP_MOTIFS",
  ANNULER_ACTION_R: "ANNULER_ACTION_R",
};
