export const TypeClientActionType = {
  GET_ERRORS: "GET_ERRORS",
  GET_TYPES_CLIENT: "GET_TYPES_CLIENT",
  ADD_TYPE_CLIENT_SUCCESS: "ADD_TYPE_CLIENT_SUCCESS",
  ADD_TYPE_CLIENT_FAILED: "ADD_TYPE_CLIENT_FAILED",
  UPDATE_TYPE_CLIENT_SUCCESS: "UPDATE_TYPE_CLIENT_SUCCESS",
  UPDATE_TYPE_CLIENT_FAILED: "UPDATE_TYPE_CLIENT_FAILED",
  DELETE_TYPE_CLIENT_SUCCESS: "DELETE_TYPE_CLIENT_SUCCESS",
  DELETE_TYPE_CLIENT_FAILED: "DELETE_TYPE_CLIENT_FAILED",
  ANNULER_ACTION: "ANNULER_ACTION",
};
