export const CarteActionType = {
  GET_ERRORS: "GET_ERRORS",
  GET_CARTES: "GET_CARTES",
  ADD_CARTE_SUCCESS: "ADD_CARTE_SUCCESS",
  ADD_CARTE_FAILED: "ADD_CARTE_FAILED",
  UPDATE_CARTE_SUCCESS: "UPDATE_CARTE_SUCCESS",
  UPDATE_CARTE_FAILED: "UPDATE_CARTE_FAILED",
  DELETE_CARTE_SUCCESS: "DELETE_CARTE_SUCCESS",
  DELETE_CARTE_FAILED: "DELETE_CARTE_FAILED",
  ANNULER_ACTION_C: "ANNULER_ACTION_C",
};
