export const TypeServiceActionType = {
  GET_ERRORS: "GET_ERRORS",
  GET_TYPES_SERVICE: "GET_TYPES_SERVICE",
  ADD_TYPE_SERVICE_SUCCESS: "ADD_TYPE_SERVICE_SUCCESS",
  ADD_TYPE_SERVICE_FAILED: "ADD_TYPE_SERVICE_FAILED",
  UPDATE_TYPE_SERVICE_SUCCESS: "UPDATE_TYPE_SERVICE_SUCCESS",
  UPDATE_TYPE_SERVICE_FAILED: "UPDATE_TYPE_SERVICE_FAILED",
  DELETE_TYPE_SERVICE_SUCCESS: "DELETE_TYPE_SERVICE_SUCCESS",
  DELETE_TYPE_SERVICE_FAILED: "DELETE_TYPE_SERVICE_FAILED",
  ANNULER_ACTION_TS: "ANNULER_ACTION_TS",
};
