export const MotifActionType = {
  GET_ERRORS: "GET_ERRORS",
  GET_MOTIFS: "GET_MOTIFS",
  ADD_MOTIF_SUCCESS: "ADD_MOTIF_SUCCESS",
  ADD_MOTIF_FAILED: "ADD_MOTIF_FAILED",
  UPDATE_MOTIF_SUCCESS: "UPDATE_MOTIF_SUCCESS",
  UPDATE_MOTIF_FAILED: "UPDATE_MOTIF_FAILED",
  DELETE_MOTIF_SUCCESS: "DELETE_MOTIF_SUCCESS",
  DELETE_MOTIF_FAILED: "DELETE_MOTIF_FAILED",
  ANNULER_ACTION_M: "ANNULER_ACTION_M",
};
