export const MarketActionType = {
    GET_ERRORS : 'GET_ERRORS',
    GET_MARKETS :'GET_MARKETS',
    ADD_MARKET_SUCCESS: 'ADD_MARKET_SUCCESS',
    ADD_MARKET_FAILED: 'ADD_MARKET_FAILED',
    UPDATE_MARKET_SUCCESS : 'UPDATE_MARKET_SUCCESS',
    UPDATE_MARKET_FAILED: 'UPDATE_MARKET_FAILED',
    DELETE_MARKET_SUCCESS : 'DELETE_MARKET_SUCCESS',
    DELETE_MARKET_FAILED : 'DELETE_MARKET_FAILED',
    ANNULER_ACTION : 'ANNULER_ACTION'

}