export const BilanActionType = {
  GET_ERRORS: "GET_ERRORS",
  GET_BILANS: "GET_BILANS",
  ADD_BILAN_SUCCESS: "ADD_BILAN_SUCCESS",
  ADD_BILAN_FAILED: "ADD_BILAN_FAILED",
  UPDATE_BILAN_SUCCESS: "UPDATE_BILAN_SUCCESS",
  UPDATE_BILAN_FAILED: "UPDATE_BILAN_FAILED",
  DELETE_BILAN_SUCCESS: "DELETE_BILAN_SUCCESS",
  DELETE_BILAN_FAILED: "DELETE_BILAN_FAILED",
  ANNULER_ACTION: "ANNULER_ACTION",
};
