export const StatutActionType = {
  GET_ERRORS: "GET_ERRORS",
  GET_STATUTS: "GET_STATUTS",
  ADD_STATUT_SUCCESS: "ADD_STATUT_SUCCESS",
  ADD_STATUT_FAILED: "ADD_STATUT_FAILED",
  UPDATE_STATUT_SUCCESS: "UPDATE_STATUT_SUCCESS",
  UPDATE_STATUT_FAILED: "UPDATE_STATUT_FAILED",
  DELETE_STATUT_SUCCESS: "DELETE_STATUT_SUCCESS",
  DELETE_STATUT_FAILED: "DELETE_STATUT_FAILED",
  ANNULER_ACTION_S: "ANNULER_ACTION_S",
};
